In [12]:
import pandas as pd

path = "out_system_day/esp-system__esp_1006__run_00000.parquet"

df = pd.read_parquet(path)

print("shape:", df.shape)
print("\ncolumns:")
print(df.columns.tolist())

print("\ndtypes:")
print(df.dtypes)

print("\nhead:")
display(df.head())

shape: (1440, 48)

columns:
['value_date', 'esp_id', 'run_id', 'stage_num', 'pump_freq_hz', 'p_int_atma', 't_int_c', 'gamma_g', 'gamma_o', 'gamma_w', 'rsb_m3m3', 'rp_m3m3', 'pb_atma', 't_res_c', 'bob_m3m3', 'muob_cp', 'fw_fr', 'q_gas_free_sm3day', 'q_liq_sm3day', 'mu_mix_cst', 'gas_fraction_d', 'q_mix_rc_m3day', 'p_dis_atma', 't_dis_c', 'head_m', 'eff_esp_d', 'power_fluid_w', 'power_esp_w', 'system_eff_d', 'u_surf_v', 'motor_u_nom_lin_v', 'motor_p_nom_kw', 'motor_f_nom_hz', 'motor_eff_nom_fr', 'motor_cosphi_nom_fr', 'motor_slip_nom_fr', 'motor_id', 'motor_u_lin_v', 'motor_i_lin_a', 'motor_cosphi', 'motor_slip', 'motor_eff_d', 'motor_p_shaft_kw', 'motor_p_electr_kw', 'motor_power_cs_kw', 'motor_eff_full_d', 'motor_load_d', 'motor_speed_rpm']

dtypes:
value_date             datetime64[us]
esp_id                            str
run_id                          int64
stage_num                       int64
pump_freq_hz                  float64
p_int_atma                    float64
t_int_c                       float64
gamma_g                       float64
gamma_o                       float64
gamma_w                       float64
rsb_m3m3                      float64
rp_m3m3                       float64
pb_atma                       float64
t_res_c                       float64
bob_m3m3                      float64
muob_cp                       float64
fw_fr                         float64
q_gas_free_sm3day             float64
q_liq_sm3day                  float64
mu_mix_cst                    float64
gas_fraction_d                float64
q_mix_rc_m3day                float64
p_dis_atma                    float64
t_dis_c                       float64
head_m                        float64
eff_esp_d                     float64
power_fluid_w                 float64
power_esp_w                   float64
system_eff_d                  float64
u_surf_v                      float64
motor_u_nom_lin_v             float64
motor_p_nom_kw                float64
motor_f_nom_hz                float64
motor_eff_nom_fr              float64
motor_cosphi_nom_fr           float64
motor_slip_nom_fr             float64
motor_id                        int64
motor_u_lin_v                 float64
motor_i_lin_a                 float64
motor_cosphi                  float64
motor_slip                    float64
motor_eff_d                   float64
motor_p_shaft_kw              float64
motor_p_electr_kw             float64
motor_power_cs_kw             float64
motor_eff_full_d              float64
motor_load_d                  float64
motor_speed_rpm               float64
dtype: object

head:

,value_date,esp_id,run_id,stage_num,pump_freq_hz,p_int_atma,t_int_c,gamma_g,gamma_o,gamma_w,...,motor_i_lin_a,motor_cosphi,motor_slip,motor_eff_d,motor_p_shaft_kw,motor_p_electr_kw,motor_power_cs_kw,motor_eff_full_d,motor_load_d,motor_speed_rpm
0,2020-01-01 00:00:00,1006,0,250,50.000000,120.0,60.0,0.7,0.86,1.0,...,18.387444,0.792662,0.017649,0.808230,20.403512,25.244687,26.782088,0.761834,0.443095,2947.052002
1,2020-01-01 00:01:00,1006,0,250,49.114919,120.0,60.0,0.7,0.86,1.0,...,18.337064,0.765250,0.016835,0.800651,19.459754,24.304906,25.785075,0.754691,0.429859,2897.285493
2,2020-01-01 00:02:00,1006,0,250,48.285667,120.0,60.0,0.7,0.86,1.0,...,18.382110,0.736985,0.016098,0.792746,18.601550,23.464692,24.893692,0.747239,0.417645,2850.502766
3,2020-01-01 00:03:00,1006,0,250,47.506144,120.0,60.0,0.7,0.86,1.0,...,18.511036,0.708168,0.015423,0.784496,17.812235,22.705310,24.088064,0.739463,0.406207,2806.406286
4,2020-01-01 00:04:00,1006,0,250,46.771391,120.0,60.0,0.7,0.86,1.0,...,18.741310,0.679978,0.014846,0.776335,17.135815,22.072714,23.416942,0.731770,0.396688,2764.621558

In [13]:
# Проверка временной оси
print("min timestamp:", df["value_date"].min())
print("max timestamp:", df["value_date"].max())

print("\nunique step:")
print(df["value_date"].diff().dropna().unique())

# Есть ли пропуски
print("\nNaNs per column:")
print(df.isna().sum())

# Простая статистика
print("\ndescribe:")
display(df.describe())

min timestamp: 2020-01-01 00:00:00
max timestamp: 2020-01-01 23:59:00

unique step:
<TimedeltaArray>
['0 days 00:01:00']
Length: 1, dtype: timedelta64[us]

NaNs per column:
value_date             0
esp_id                 0
run_id                 0
stage_num              0
pump_freq_hz           0
p_int_atma             0
t_int_c                0
gamma_g                0
gamma_o                0
gamma_w                0
rsb_m3m3               0
rp_m3m3                0
pb_atma                0
t_res_c                0
bob_m3m3               0
muob_cp                0
fw_fr                  0
q_gas_free_sm3day      0
q_liq_sm3day           0
mu_mix_cst             0
gas_fraction_d         0
q_mix_rc_m3day         0
p_dis_atma             0
t_dis_c                0
head_m                 0
eff_esp_d              0
power_fluid_w          0
power_esp_w            0
system_eff_d           0
u_surf_v               0
motor_u_nom_lin_v      0
motor_p_nom_kw         0
motor_f_nom_hz         0
motor_eff_nom_fr       0
motor_cosphi_nom_fr    0
motor_slip_nom_fr      0
motor_id               0
motor_u_lin_v          0
motor_i_lin_a          0
motor_cosphi           0
motor_slip             0
motor_eff_d            0
motor_p_shaft_kw       0
motor_p_electr_kw      0
motor_power_cs_kw      0
motor_eff_full_d       0
motor_load_d           0
motor_speed_rpm        0
dtype: int64

describe:

,value_date,run_id,stage_num,pump_freq_hz,p_int_atma,t_int_c,gamma_g,gamma_o,gamma_w,rsb_m3m3,...,motor_i_lin_a,motor_cosphi,motor_slip,motor_eff_d,motor_p_shaft_kw,motor_p_electr_kw,motor_power_cs_kw,motor_eff_full_d,motor_load_d,motor_speed_rpm
count,1440,1440.0,1440.0,1.440000e+03,1440.0,1440.0,1.440000e+03,1.440000e+03,1440.0,1440.0,...,1.440000e+03,1440.000000,1440.000000,1.440000e+03,1440.000000,1.440000e+03,1.440000e+03,1.440000e+03,1.440000e+03,1.440000e+03
mean,2020-01-01 11:59:30,0.0,250.0,3.399175e+00,120.0,60.0,7.000000e-01,8.600000e-01,1.0,100.0,...,8.947808e+20,0.118504,0.000577,4.964237e-02,0.627993,1.487060e+20,1.577622e+20,9.140583e-02,2.513869e+15,2.027486e+02
min,2020-01-01 00:00:00,0.0,250.0,1.085314e-20,120.0,60.0,7.000000e-01,8.600000e-01,1.0,100.0,...,1.596110e+01,0.095951,0.000001,-2.851811e-01,0.000000,3.758688e+00,8.229628e+00,5.367769e-21,-4.993648e-02,6.511876e-19
25%,2020-01-01 05:59:45,0.0,250.0,8.488029e-15,120.0,60.0,7.000000e-01,8.600000e-01,1.0,100.0,...,9.975918e+04,0.095951,0.000001,1.695474e-22,0.000000,1.657924e+04,1.764052e+04,4.198028e-15,3.534176e-01,5.092812e-13
50%,2020-01-01 11:59:30,0.0,250.0,6.637745e-09,120.0,60.0,7.000000e-01,8.600000e-01,1.0,100.0,...,7.801337e+10,0.095951,0.000001,1.325882e-16,0.000000,1.296525e+10,1.375483e+10,3.282911e-09,2.191770e+05,3.982643e-07
75%,2020-01-01 17:59:15,0.0,250.0,5.190368e-03,120.0,60.0,7.000000e-01,8.600000e-01,1.0,100.0,...,6.100201e+16,0.095951,0.000001,1.036531e-10,0.000000,1.013809e+16,1.075549e+16,2.559550e-03,1.713839e+11,3.114217e-01
max,2020-01-01 23:59:00,0.0,250.0,5.000000e+01,120.0,60.0,7.000000e-01,8.600000e-01,1.0,100.0,...,4.769577e+22,0.792662,0.017649,8.082299e-01,20.403512,7.926686e+21,8.409421e+21,7.934494e-01,1.340003e+17,2.947052e+03
std,NaN,0.0,0.0,9.501917e+00,0.0,0.0,1.110609e-16,1.110609e-16,0.0,0.0,...,4.577657e+21,0.080237,0.002048,1.667150e-01,2.290764,7.607729e+20,8.071040e+20,2.044660e-01,1.286083e+16,5.659275e+02

In [14]:
for col in df.columns:
    print(f"\n--------------------------- {col} ---------------------------")
    print(df[col].head(5).to_list())

--------------------------- value_date ---------------------------
[Timestamp('2020-01-01 00:00:00'), Timestamp('2020-01-01 00:01:00'), Timestamp('2020-01-01 00:02:00'), Timestamp('2020-01-01 00:03:00'), Timestamp('2020-01-01 00:04:00')]

--------------------------- esp_id ---------------------------
['1006', '1006', '1006', '1006', '1006']

--------------------------- run_id ---------------------------
[0, 0, 0, 0, 0]

--------------------------- stage_num ---------------------------
[250, 250, 250, 250, 250]

--------------------------- pump_freq_hz ---------------------------
[50.0, 49.11491935363973, 48.28566697138496, 47.50614385052375, 46.77139104259065]

--------------------------- p_int_atma ---------------------------
[120.0, 120.0, 120.0, 120.0, 120.0]

--------------------------- t_int_c ---------------------------
[60.0, 60.0, 60.0, 60.0, 60.0]

--------------------------- gamma_g ---------------------------
[0.7, 0.7, 0.7, 0.7, 0.7]

--------------------------- gamma_o ---------------------------
[0.86, 0.86, 0.86, 0.86, 0.86]

--------------------------- gamma_w ---------------------------
[1.0, 1.0, 1.0, 1.0, 1.0]

--------------------------- rsb_m3m3 ---------------------------
[100.0, 100.0, 100.0, 100.0, 100.0]

--------------------------- rp_m3m3 ---------------------------
[100.0, 100.0, 100.0, 100.0, 100.0]

--------------------------- pb_atma ---------------------------
[130.0, 130.0, 130.0, 130.0, 130.0]

--------------------------- t_res_c ---------------------------
[80.0, 80.0, 80.0, 80.0, 80.0]

--------------------------- bob_m3m3 ---------------------------
[1.2, 1.2, 1.2, 1.2, 1.2]

--------------------------- muob_cp ---------------------------
[1.5, 1.5, 1.5, 1.5, 1.5]

--------------------------- fw_fr ---------------------------
[0.3, 0.3, 0.3, 0.3, 0.3]

--------------------------- q_gas_free_sm3day ---------------------------
[0.0, 0.0, 0.0, 0.0, 0.0]

--------------------------- q_liq_sm3day ---------------------------
[60.0, 60.06254343293954, 60.125086865879084, 60.187630298818625, 60.25017373175817]

--------------------------- mu_mix_cst ---------------------------
[1.898298874899209, 1.8982988748992087, 1.8982988748992087, 1.8982988748992087, 1.898298874899209]

--------------------------- gas_fraction_d ---------------------------
[0.0051022918445562514, 0.005102291844556209, 0.005102291844556164, 0.0051022918445561205, 0.005102291844556279]

--------------------------- q_mix_rc_m3day ---------------------------
[68.31654729450175, 68.3877598177413, 68.45897234098089, 68.53018486422047, 68.60139738746004]

--------------------------- p_dis_atma ---------------------------
[246.0909521732542, 241.20575319688092, 236.68016528162087, 232.47341986129948, 228.80546655694772]

--------------------------- t_dis_c ---------------------------
[64.91639948617677, 64.63517687646338, 64.38231551934935, 64.15399588329025, 63.9600721715018]

--------------------------- head_m ---------------------------
[1502.584237542312, 1444.5303327039537, 1390.7458820189029, 1340.7467438970184, 1297.1478175730458]

--------------------------- eff_esp_d ---------------------------
[0.4959360209705014, 0.5008457300458588, 0.5054151108490731, 0.5096656583179461, 0.5133751001911642]

--------------------------- power_fluid_w ---------------------------
[9889.305956661916, 9517.233773907308, 9172.512663143048, 8852.035382292344, 8573.158051473294]

--------------------------- power_esp_w ---------------------------
[19940.688997160258, 19002.3258719524, 18148.473336568168, 17368.31830401678, 16699.598496851384]

--------------------------- system_eff_d ---------------------------
[0.3692507399625587, 0.36909854559837213, 0.368467350405669, 0.36748638474252415, 0.36610919882109366]

--------------------------- u_surf_v ---------------------------
[1000.0, 1000.0, 1000.0, 1000.0, 1000.0]

--------------------------- motor_u_nom_lin_v ---------------------------
[1000.0, 1000.0, 1000.0, 1000.0, 1000.0]

--------------------------- motor_p_nom_kw ---------------------------
[45.0, 45.0, 45.0, 45.0, 45.0]

--------------------------- motor_f_nom_hz ---------------------------
[50.0, 50.0, 50.0, 50.0, 50.0]

--------------------------- motor_eff_nom_fr ---------------------------
[0.85, 0.85, 0.85, 0.85, 0.85]

--------------------------- motor_cosphi_nom_fr ---------------------------
[0.9, 0.9, 0.9, 0.9, 0.9]

--------------------------- motor_slip_nom_fr ---------------------------
[0.04, 0.04, 0.04, 0.04, 0.04]

--------------------------- motor_id ---------------------------
[2, 2, 2, 2, 2]

--------------------------- motor_u_lin_v ---------------------------
[1000.0, 1000.0, 1000.0, 1000.0, 1000.0]

--------------------------- motor_i_lin_a ---------------------------
[18.38744433171477, 18.337064198221224, 18.382109931126347, 18.51103644144283, 18.741310202844016]

--------------------------- motor_cosphi ---------------------------
[0.7926619135959684, 0.7652503219586919, 0.7369853803575672, 0.7081676363438802, 0.6799784722117433]

--------------------------- motor_slip ---------------------------
[0.01764933263585934, 0.016834555002407242, 0.016097686583482776, 0.015423389425005943, 0.014845935969826269]

--------------------------- motor_eff_d ---------------------------
[0.8082299349916368, 0.8006512588801071, 0.7927463800471019, 0.7844964603365118, 0.7763347324131101]

--------------------------- motor_p_shaft_kw ---------------------------
[20.403511697978768, 19.459753946058417, 18.60154969233149, 17.812235437913436, 17.135814663832644]

--------------------------- motor_p_electr_kw ---------------------------
[25.244686956800102, 24.30490644987845, 23.4646920635907, 22.705310142856263, 22.07271418936617]

--------------------------- motor_power_cs_kw ---------------------------
[26.782088392469227, 25.78507525267605, 24.893691810263377, 24.08806353055621, 23.416942483498573]

--------------------------- motor_eff_full_d ---------------------------
[0.761834230362557, 0.7546906012631793, 0.7472394948129908, 0.7394631542431066, 0.7317699428910454]

--------------------------- motor_load_d ---------------------------
[0.44309525171035286, 0.4298590027645744, 0.41764533414669375, 0.4062074240153954, 0.3966879789853262]

--------------------------- motor_speed_rpm ---------------------------
[2947.052002092422, 2897.285492540525, 2850.502766280311, 2806.406285630206, 2764.6215579571585]